<?php

/**
 * @file
 * Miscellaneous hook implementations.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_islandora_solr_query().
 *
 * Adds a collection as a filter if it is defined in the url params.
 */
function islandora_collection_search_islandora_solr_query($islandora_solr_query) {
  $query = \Drupal::request()->query;
  // Exit early if the collection PID isn't set in the URL params.
  if (!$query->has('cp')) {
    return;
  }

  // Grab the collection pid and add it as a Solr query filter.
  $collection_pid = $query->get('cp');
  $ancestor_field = \Drupal::config('islandora_collection_search.settings')->get('islandora_collection_search_ancestor_field');
  $filter = strtr('!field:"!value"', [
    '!field' => $ancestor_field,
    '!value' => $collection_pid,
  ]);
  $islandora_solr_query->solrParams['fq'][] = $filter;
}

/**
 * Implements hook_form_alter().
 *
 * Adds a submit handler to any form that can potentially alter the object
 * hierarchy (e.g. changing parents, etc...).
 */
function islandora_collection_search_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'islandora_basic_collection_migrate_children_form':
    case 'islandora_basic_collection_share_children_form':
    case 'islandora_basic_collection_delete_children_form':
      $form['#submit'][] = 'islandora_collection_search_collection_form_submit';
      break;
  }
}

/**
 * Re-indexes all children of the object(s) manipulated by a form.
 *
 * @param array $form
 *   Array of drupal form api elements.
 * @param Drupal\Core\Form\FormStateInterface $form_state
 *   Array representing the form state.
 */
function islandora_collection_search_collection_form_submit(array $form, FormStateInterface $form_state) {
  // Grab the initial list of children that are being migrated from the form.
  $children = array_keys(array_filter($form_state->getValue('children')));
  module_load_include('inc', 'islandora_collection_search', 'includes/batch');
  batch_set(islandora_collection_search_reindex_descendants_batch($children));
}

/**
 * Implements hook_form_FORMID_alter().
 */
function islandora_collection_search_form_islandora_solr_advanced_search_form_alter(array &$form, FormStateInterface $form_state) {
  if (\Drupal::config('islandora_collection_search.settings')->get('islandora_collection_search_advanced_search_alter')) {
    module_load_include('inc', 'islandora_collection_search', 'includes/utilities');
    $default_options = [
      'all' => t('All collections'),
    ];
    $collections = islandora_collection_search_retrieve_searchable_collections($default_options, FALSE);
    $form['collections'] = [
      '#type' => 'select',
      '#options' => $collections,
      '#weight' => 5,
    ];
    $form['controls']['#weight'] = 6;
    $form['#submit'][] = 'islandora_collection_search_append_collection_pid';
  }
}

/**
 * Submit handler which appends the collection PID to the query.
 *
 * @param array $form
 *   An array representing a form within Drupal.
 * @param Drupal\Core\Form\FormStateInterface $form_state
 *   An array representing the Drupal form state.
 */
function islandora_collection_search_append_collection_pid(array $form, FormStateInterface $form_state) {
  if ($form_state->getValue('collections') != 'all') {
    $redirect = $form_state->getRedirect();
    $options = $redirect->getOptions();
    $options['query']['cp'] = $form_state->getValue('collections');
    $redirect->setOptions($options);
  }
}

/**
 * Implements hook_help().
 */
function islandora_collection_search_help($route) {
  switch ($route) {
    // Main help page for the module.
    case 'help.page.islandora_collection_search':
      // About section.
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t(
        'The Islandora Collection Search module provides a Block similar to
        the "Simple Search" Block provided by Islandora Solr. When this Block
        is set to search all collections, it functions exactly like the "Simple
        Seach" Block; the key difference for the "Islandora Collection Search"
        Block is referenced in its name: it allows users to limit searches to
        a specific collection. The Collections available to be searched depend
        on the configuration on your website. Configuration details can be
        found on the module\'s <a href=":readme">README</a>.', [
          ':readme' => 'https://github.com/discoverygarden/islandora_collection_search/blob/8.x/README.md',
        ]
      ) .
      '</p>';
      // Uses section.
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dt>' . t('Searching') . '</dt><dd>' . t(
        'As long as the "Islandora Collection Search" Block is configured
        correctly, things should not be too complicated. Select the desired
        collection to search from the drop-down, and type your keywords in
        the search field.'
      ) .
      '</dd>';
      return $output;

    // Other cases can be added for various admin pages.
  }
}
